server:
  port: 8000

spring:
  application:
    name: provider   #注册到Eureka Server上的应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    #注册的位置
  instance:
    prefer-ip-address: true  #将自己的ip注册到EuekaServer上